resources:
 repositories:
 - repository: templates
   type: github
   name:  SergeyTorotska/test
   endpoint: TaskAzure

pool: Azure Pipeline

stages:

- template: build-template.yml .yml@templates

- stage: Publish
  jobs:
    - job: PublishJob
      steps:
      - task: DotNetCoreCLI@2
        displayName: 'dotnet publish'
        inputs:
          command: publish
          arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'