trigger:
  branches:
    include:
      - dev
    
pr:
  branches:
    include:
      - dev
      - master

pool: Azure Pipeline
 
steps:
  - task: DotNetCoreCLI@2
    displayName: 'dotnet restore'
    inputs:
      command: 'restore'
      projects: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: '255f8b5e-0d73-4208-a824-b04c39407d41'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      projects: '**/*.sln' 
      arguments: '--configuration Release' 
  
  - task: DotNetCoreCLI@2
    displayName: 'dotnet test (unit)'
    inputs:
      command: test
      projects: 'tests/Unit/**/*.csproj'
      arguments: '--configuration Release'
  - task: DotNetCoreCLI@2
    displayName: 'dotnet publish'
    inputs:
     command: publish
     arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  - task: PublishPipelineArtifact@1
    displayName: 'Publish Pipeline Artifact'
    inputs:
      targetPath: '$(DatabaseMigrationProjectPath)'
      artifact: DB       